### PR TITLE
Add support for UKTV Play

### PR DESCRIPTION
**Pull request by BB21B**
Added support for UKTV Play, tested on my Bravia Android TV.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Hi, sorry for the late reply. LGTM. Will merge.

Just an FYI - I will not be able to upload an APK for another week or so.

**Comment by hoshsadiq** [comment]
Thank you for your contributions!

**Comment by BB21B** [comment]
Cheers, glad I could help.

**Comment by hoshsadiq** [comment]
FYI - the artifacts have been uploaded

**Pull request merged**
