### PR TITLE
Oreo changes

### PR DESCRIPTION
**Pull request by falo2k**
The Oreo update has totally messed with this.  Trying a few virtual devices it looks like 8.0 won't allow multiple launchers, 8.1 will, and 9.0 won't.  I can't find any documentation on this change.

My alternative suggestion is to split the apks.  I've re-written the launcher to be generic and then take different flavors for the icon & string changes.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Great! You've done it a lot cleaner than I could have dreamed of with my zero Android dev skills. I've got no CI so will merge this soon as my local machine is fixed and will upload the APKs. Thanks for contributing!

**Comment by falo2k** [comment]
Oh, this is pure hackery - this is where my Android knowledge stops :)  There's no exception handling beyond a bit of a catch and throw!

I completely forgot to update the Readme so you may want to reflect the multiple apk thing in there.

**Comment by irving93** [comment]
Iam wondering if you could make a shortcut to the STV player version instead of the itv hub? Is this possible?

**Comment by falo2k** [comment]
Is the STV app deployed by Sony if you select your region as Scotland then?  If so it should be possible.  Need to get a logtrace done on the TV while firing up the app to find out the relevant parameters to pass (unless @hoshsadiq had another way to find these out).  If you activate dev mode on the TV, connect adb and run a trace and filter on HbbTv then you can see the parameters in the logs.  Then it should be as simple as creating a new folder for STV with the right icons and parameters in the resources, add the stv gradle entry, and let the build do the work.

**Comment by hoshsadiq** [comment]
I'll merge this for now. I'll upload the APKs in the next few days.

**Pull request merged**
